import type { RcaGetResult } from '@flakemetry/contracts'

const percent = (value: number): string => `${Math.round(value * 100)}%`

export const RcaPanel = ({
  report,
  errorMessage,
}: {
  report: RcaGetResult
  errorMessage: string | null
}) => (
  <div className="card rca">
    <div className="row-between" style={{ marginBottom: '0.75rem' }}>
      <strong>Root cause analysis</strong>
      {report ? (
        <span className="muted" style={{ fontSize: '0.8rem' }}>
          {report.llmModel} · {report.tokenCost.toLocaleString()} tokens
        </span>
      ) : null}
    </div>

    {errorMessage ? (
      <div className="error-box mono">{errorMessage}</div>
    ) : (
      <p className="muted">This execution recorded no error message.</p>
    )}

    {report ? (
      <>
        <p style={{ marginBottom: '0.75rem' }}>{report.summary}</p>

        <div className="rca-grid">
          <div>
            <div className="rca-label">Likely cause</div>
            <div>{report.likelyCause}</div>
          </div>
          <div>
            <div className="rca-label">Suggested action</div>
            <div>{report.suggestedAction}</div>
          </div>
          <div>
            <div className="rca-label">Confidence</div>
            <div>{percent(report.confidence)}</div>
          </div>
        </div>

        {report.similarPast.length > 0 ? (
          <div style={{ marginTop: '0.9rem' }}>
            <div className="rca-label">Seen before</div>
            <ul className="reasons">
              {report.similarPast.map((similar) => (
                <li key={similar.signatureId}>
                  <span className="muted">{similar.summary}</span>
                  {similar.resolution ? <span> → {similar.resolution}</span> : null}
                </li>
              ))}
            </ul>
          </div>
        ) : null}

        <p className="muted" style={{ fontSize: '0.78rem', marginTop: '0.9rem', marginBottom: 0 }}>
          Generated by a language model. Treat it as a lead, not a verdict.
        </p>
      </>
    ) : (
      <p className="muted" style={{ marginBottom: 0 }}>
        No analysis for this failure yet. AI root-cause analysis runs asynchronously and is
        budget-gated; when it is enabled and has processed this failure, the explanation appears
        here.
      </p>
    )}
  </div>
)
