apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flakemetry.fullname" . }}-api
  labels:
    {{- include "flakemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flakemetry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "flakemetry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "flakemetry.serviceAccountName" . }}
      {{- with .Values.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: {{ include "flakemetry.image" (dict "root" $ "name" .Values.api.image.name "tag" .Values.api.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
          env:
            - name: PORT
              value: {{ .Values.api.port | quote }}
            {{- include "flakemetry.commonEnv" . | nindent 12 }}
            {{- with .Values.api.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
